service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  # iam:
  #   role:
  #     statements:
  #       - Effect: Allow
  #         Action: 'dynamodb:*'
  #         Resource: ''

plugins:
  - serverless-offline
  - serverless-dynamodb

custom:
  serverless-dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions:
  get-users:
    handler: greeting.getUsers
    events:
      - http:
          path: users/{id}
          method: GET

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

