name: Serverless Deployment
on:
  push:
    branches:
      - main
    
jobs:
  ssr-deployment:
    runs-on: ubuntu-20.04
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      # Step 3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Installing  dependencies
        if: steps.cached-npm-dependencies.output.cache-hit != 'true'
        run: |
          npm install   

      - name: Deploy Lambda
        id: deploy
        run: | 
          npx sls deploy